- src/scss/elements/_typography.scss
The current letterspacing for `caps` is quite wide:
I removed that letterspacing to make it look correct:
> fix(caps utility): remove massive letter-spacing from .caps class

- src/scss/elements/_forms.scss
The current radio button in Namely has a `:checked:before` border width.  This resets to 0, fixing my googly-eyes radio buttons in the PTO build.
> another huge one

- package.json
Adds node-fetch as a dependency for calls to an API.
Allows for use of fetcher conventions for allowing actions / stores to interact with an API as seen here:
https://reactjsnews.com/getting-started-with-flux/
> [RFC] Adds Fetch To Stack

- package.json
- src/js/fetcher.js
Depends on: https://github.com/namely/styleguide/pull/70
Allows components / actions / stores to make api requests using a fetcher.
example: ```fetcher("http://echo.jsontest.com/key/value/one/two", this.getResponse)```
Once the fetcher is imported, it takes a *full* URL and a callback as parameters.
> [RFC] Creates Simple Fetcher Wrapper for API Calls

- scss-lint.yml
- src/scss/animations/_easing.scss
- src/scss/animations/_fade.scss
- src/scss/animations/_zoom.scss
Finally took some time fix some pestering scss-lint warnings. scss-lint currently ignores the `_select.scss` partial for SelectorFormat until we fork and fix the third-party component or replace it with something else.
> fix(styles): no more scss-lint errors

- src/scss/base/_states.scss
- src/scss/base/_tables.scss
Based off of @tsargent's PR #78, `.hover-row` is more general utility for adding this type of interactive state to any "row" of data, as it is a common pattern around the Namely app. i.e. 
I wanted to make edits to Tyler's PR but I didn't have the push permissions. :shrug:
> hover-row utility

- src/js/components/buttons/button.js
- src/js/pages/buttons.js
- src/scss/elements/buttons/_types.scss
This is an addition to the group of `button-link` type Buttons for the styleguide. It is needed for this feature: 
http://quick.as/xnYCZgrd
> adds button-baby as button-link option

- Gulpfile.js
- README.md
This allows us to serve the styleguide locally on a port other than 8080:
```
$ gulp --port 8081
```
If `--port ` isn't set, defaults to 8080.
Useful for serving Namely and the stylguide at the same time.
> allows gulp connect to run on other ports

- src/scss/elements/_forms.scss
Since the our radio button is really constructed with `::before` and `::after` pseudo-elements, this actually doesn't change the size, but corrects the alignment of radio buttons by setting the element's width and height to the sum of its border and `::after` pseudo-element:
Before:
After:
> fixes radio size

- src/scss/elements/_typography.scss
This would be nice for something I'm building for banking.  There's a routing number field, and the bank name appears on the right side of the field, kind of like a text field placeholder, but permanent:
(ignore the error messages)
I think it would be nice to set `user-select: none` on this.  I can see this utility be used elsewhere, like on certain labels, etc.
> add utility class for user-select: none

- package.json
Right now namely/namely is using a branch of this repo called `react-upgrade` that was made to use the latest stable version of React for both this repo and the Namely app. Since DND, including the react upgrade, has been merged with develop and production, Namely/Namely is still using that outdated branch.
This PR is just to upgrade this repo to React v0.13.3 before changing namely/namely back to using the master branch. Once this is merged, a PR will be made on namely/namely to fix the package.json. 
Note:
I'll be making an issue for researching a better way of keep the React version between the two repos in sync.
> feat: upgrade namely-ui to use react v0.13.3

- package.json
Was having trouble with node-sass when dealing with different, newer-ish versions of node. Traced it back to gulp-sass which could use a slight version bump to address performance / bugs.
*gulp-sass changelog*
https://github.com/dlmanning/gulp-sass/blob/master/CHANGELOG.md#v201
*depends on*
https://github.com/namely/styleguide/pull/182
> updates gulp-sass to 2.0.4

- src/js/pages/icons.js
- src/lib/scss/_icons-template.scss
- src/scss/base/_icons.scss
Adds `vertical-align: middle;` to `_icons-template.scss`.
***before***
***after***
> Vertically Aligns Icons to the Middle

- package.json
Just realized that I was still listed as the author of the namely-ui package, which is silly. This PR changes the `author` to Namely and lists everyone on the front-end team in the `contributors` field. Please let me know if I missed anyone.
> updates author and contributors in package.json

- karma.conf.js
- package.json
This copies the Karma setup by @johnnymo87 in the Namely app, and allows Karma to use Chrome with HTML reporting, for Chrome Dev Tools and this nice report:
This is still optional for the user and doesn't start automatically; command to use is
```
karma start --browsers Chrome
```
> Add Chrome as a Karma browser option

- .npmignore
- package.json
- scripts/prepublish.sh
I think this fixes the postinstall.  `src/` should removed from `.npmignore` because the scripts moves files from that directory to the root.
I moved it right to the postinstall hook since it's just one command.
Please confirm this works before giving a plus one:
In your namely package.json, set the namely-ui dependency like this:
```
"namely-ui": "tsargent/styleguide#develop",
```
This will install namely-ui from my fork.  
Then do 
```shell
$ ls node_modules/namely-ui
```
from inside the namely app to confirm `buttons/`, `forms/` etc show up.
> fix postinstall

- src/js/components/forms/fields/select/select.es6
- src/js/pages/forms.js
adding `ref=simpleSelect` allows us to get the value from the select field's parent component
Not sure if I like this, but and wondering what other people think.  Accessing the value from the event wasn't really working, since we're not using an actual html select here.
> get value from simpleSelect

- src/js/components/forms/edit-label.es6
- src/js/components/forms/fields/checkbox.es6
- src/js/components/forms/fields/date/date.es6
- src/js/components/forms/fields/number.es6
- src/js/components/forms/fields/radio.es6
- src/js/components/forms/fields/select/select.es6
- src/js/components/forms/fields/select/simple-select.es6
- src/js/components/forms/fields/text.es6
- src/js/components/forms/fields/textarea.es6
- src/js/components/overlays/tooltip.es6
- src/js/pages/forms.js
- src/scss/elements/_forms.scss
- test/forms/fields/select/simple-select.spec.js
I don't think we need to pass props for 'field-light', et al. to all of our field components. This can be accomplished by styling children of the native `fieldset` node and the `.tooltip` class.
I'd started working on a FieldSet component and it was completely dumb, no props or any logic, just a wrapper adding functional classes.
There are a few things like PTO plan settings that use a well-style appearance, but these can be styled using functional classes. Default styles should cover all other cases.
This PR covers the following tasks:
> Fieldsets / Wells

- circle.yml
- package.json
All pull requests merged into master will trigger a deploy to Surge once CI passes. No need to install the surge npm package globally anymore.
> Continuous Deployment

- src/js/components/forms/fields/text.es6
- src/js/components/forms/fields/textarea.es6
- src/js/pages/forms.js
This is a hotfix (patch) for the current salary build. No breaking changes. 
I'm working on another branch to refactor the existing fields to use the upcoming `FieldBase` but this is needed before that is ready.
> fix(fields): adds 'name' props to TextField & TextAreaField

- package.json
- src/js/components/forms/fields/checkbox.es6
- src/js/components/forms/fields/date/date.es6
- src/js/components/forms/fields/file.es6
- src/js/components/forms/fields/number.es6
- src/js/components/forms/fields/radio.es6
- src/js/components/forms/fields/select/select.es6
- src/js/components/forms/fields/textarea.es6
- src/js/components/utils/omit.es6
Download chrome 43.0.2357.134 http://google-chrome.en.uptodown.com/mac/old
Login to namely locally, note `Object.assign is not a function` <img width="1348" alt="screen shot 2016-03-14 at 03 12 41" src="https://cloud.githubusercontent.com/assets/3466499/13734170/1e113fdc-e993-11e5-9c4e-bf5d2bfd0110.png">
I had to use a version of `lodash.assgin` that matched namely's, otherwise company goals would break <img width="1348" alt="screen shot 2016-03-14 at 03 07 33" src="https://cloud.githubusercontent.com/assets/3466499/13734161/fd918712-e992-11e5-8d44-216b9416e5f2.png">
> Use lodash.assign instead of Object.assign

- src/js/components/lists/index.js
- src/js/components/lists/sortable-table-header-cell.es6
- src/js/components/lists/sortable.es6
- src/js/pages/tables.js
- test/lists/sortable.spec.js
Keeps the same setup style as `Sortable` in HCM, using only other component and no `underscore` dependency. 
Video Preview: http://quick.as/zngCXXjQ
Needs:
> feat(lists/sortable-table): adds working sortable table w/ example

- src/js/components/forms/fields/checkbox.es6
- test/forms/fields/checkbox.spec.js
When getting `values` inside the CheckboxField, I attempt to grab the `elements` property from the `fieldset` node. Before today, I was not aware that property was unsupported in IE. To resolve that issue, I've created the `getElements` method in the component to use `elements` if it's defined, then fallback to `getElementsByTagName` when needed (IE). 
I've also added a test spec for this component. 
Fixes https://namely.atlassian.net/browse/BR-941
> IE fix for CheckboxField
